keywords = {
    'art & design': ['art exhibition', 'art galler', 'art', 'artist', 'design trends', 'visual art'],
    'books': ['author', 'bestseller', 'book recommendation', 'book release', 'book review', 'literature'],
    'business': ['business', 'business analysis', 'business', 'business trend', 'company', 'companies', 'corporate', 'entrepreneur', 'industry news', 'startup'],
    'crypto': ['altcoin', 'bitcoin', 'blockchain', 'crypto market', 'crypto', 'crypto trading', 'cryptocurrency', 'digital currency', 'ethereum'],
    'culture': ['cultural analysis', 'cultural event', 'cultural', 'lifestyle', 'social issue', 'societal trend'],
    'economy': ['business', 'economic indicator', 'economic', 'economy', 'finance', 'fiscal policy', 'inflation', 'market', 'monetary policy', 'stock market', 'trade'],
    'film-TV': ['actor', 'actress', 'airdate', 'comedy', 'director', 'episode', 'film', 'film festival', 'film industry', 'film release', 'film review', 'mini-series', 'movie', 'netflix', 'spoilers', 'tv', 'tv review', 'tv series', 'tv show', 'tv streaming', 'television industry', 'watch', 'watchlist'],
    'food': ['cooking tip', 'culinary trend', 'food culture', 'food', 'recipe', 'restaurant review'],
    'gaming': ['game release', 'game review', 'gaming industry', 'gaming', 'esports', 'video game'],
    'health': ['cardiovascular', 'disease', 'health', 'healthcare', 'heart', 'medical breakthrough', 'medical research', 'medicine', 'mental health', 'nutrition', 'public health', 'wellness'],
    'investing': ['investing', 'stocks', 'bonds', 'investment strateg', 'portfolio management', 'financial market', 'dividend'],
    'music': ['album', 'artist', 'band', 'concert', 'music festival', 'final tour', 'genre', 'hit single', 'music', 'music industry', 'musician', 'premiere', 'record industry', 'singer-songwriter', 'song', 'spotify'],
    'opinion': ['commentary', 'editorial', 'guest column', 'op-ed', 'opinion piece', 'perspective', 'thought piece', 'viewpoint'],
    'politics': ['administration', 'biden', 'democracy', 'election', 'federal', 'government', 'legislation', 'political analysis', 'political debate', 'political', 'political part', 'politician', 'policy', 'president', 'social security', 'supreme court', 'trump', 'white house'],
    'programming': ['app development', 'coding', 'programming language', 'programming', 'python', 'software development', 'web development'],
    'real estate': ['housing development', 'housing market', 'property', 'property investment', 'real estate', 'real estate trend'],
    'science': ['astronomy', 'breakthrough', 'chemical', 'discover', 'experiment', 'environment', 'nasa', 'pfas', 'research', 'scientific', 'scientific research', 'scientific stud', 'science', 'science news', 'space', 'space exploration', 'spacecraft', 'technology advancement', 'toxic', 'universe'],
    'sports': ['all-star', 'athlete', 'athletic', 'baseball', 'basketball', 'competitions', 'cricket', 'football', 'major sports event', 'match reports', 'nba', 'point guard', 'soccer', 'sports', 'sports analysis', 'sports news', 'tennis', 'team', 'wimbledon', 'world cup'],
    'style': ['beauty', 'design', 'fashion', 'fashion show', 'lifestyle', 'luxury', 'personal style', 'style guide', 'trend'],
    'tech': ['app store', 'artificial intelligence', 'computer', 'digital advancement', 'elon musk', 'facebook', 'google', 'gadget', 'innovation', 'internet', 'machine learning', 'netflix', 'tech compan', 'tech', 'tech trends', 'technology', 'threads', 'twitter', 'zuckerberg'],
    'travel': ['adventure', 'destination', 'explore', 'journey', 'passport', 'tourism', 'travel', 'travel guide', 'travel', 'travel tip', 'vacation'],
    'u.s.': ['america', 'american', 'us economy', 'us election', 'us government', 'us politic', 'us society', 'united states'],
    'world': ['diplomacy', 'foreign policy', 'geopolitic', 'global event', 'india', 'international', 'international relation', 'king', 'prime minister', 'prince', 'queen', 'royal', 'ukraine', 'united nations', 'world affairs'],
}
