from transformers import BartTokenizer, BartForConditionalGeneration

# initialize the model and tokenizer
model = BartForConditionalGeneration.from_pretrained('sshleifer/distilbart-xsum-12-6')
tokenizer = BartTokenizer.from_pretrained('sshleifer/distilbart-xsum-12-6')

# function to summarize text
def summarize_text(text):
    inputs = tokenizer.encode("summarize: " + text, return_tensors='pt', max_length=1024, truncation=True)
    outputs = model.generate(inputs, max_length=150, min_length=40, length_penalty=2.0, num_beams=4, early_stopping=True)
    return tokenizer.decode(outputs[0], skip_special_tokens=True)  # skip special tokens during decoding

#print(summarize_text('Michael Bisping makes it known who between Tyson Fury and Francis Ngannou has his support Fury and Ngannou are set to fight under boxing rules in October "Francis (Ngannou) can knock out Tyson Fury, that\'s a fact," Bisping says The long-awaited mega-fight between heavyweight boxing star Tyson Fury and former UFC heavyweight champion Francis Ngannou is set to take place on October 28 in Riyadh, Saudi Arabia and one of the most iconic mixed martial arts (MMA) stars is making his pick as early as now. Speaking with online sportsbook Betway , former UFC middleweight champion Michael Bisping shared some thoughts on the bout and why "The Predator" is most likely leaving the event with his hand raised. "I think the general consensus is Tyson\'s going to beat him, but you never know. Francis has got that ridiculous power and that\'s what makes it interesting. And that\'s why I\'ll pay to see it. They\'re all going to make a ton of money out of it, so well done for him," Bisping stated. "I hope he catches Fury, I shouldn\'t say that as an Englishman, but Ngannou is a mixed martial artist so I\'m kind of on his side. And we all like a shocking upset, so I wish him all the best." The reveal was made earlier this month after months and months of back and forth from two of combat sports\' most dominant heavyweights. In his most recent bout which took place last December, Fury put his WBC heavyweight title on the line against Derek Chisora and came away victorious after a TKO in the 10th round at the Tottenham Hotspur Stadium in London, England. As for Ngannou, the heavyweight monster made the decision to join the Professional Fighters League (PFL) amidst interest from other promotions like ONE Championship after he chose not to re-sign with the UFC. With the bout certain to take place, Bisping elaborated how much of a chance Ngannou actually had as he prepares to fight "The Gypsy King." "He\'s 100% got a puncher\'s chance, and you never know, if Tyson Fury takes him lightly he might pay the ultimate price. Francis Ngannou has the ability to murder you in the boxing ring, so there\'s a real risk there. If it goes to the later rounds Francis is going to get tired because it\'s not his sport, but in those first three rounds he\'s going to be ridiculously dangerous," Bisping later explained. "Francis has got phenomenal power. Tyson moves so well, he\'s taller, he\'s fought better people, but Francis (Ngannou) can knock out Tyson Fury, that\'s a fact. He has the power to knock him out and if he could bully him into the corner and let loose with a ferocious combination, you never know." Tyson Fury is victorious as he defeats Dillian Whyte during their WBC heavyweight championship fight at Wembley Stadium on April 23, 2022 in London, England. Mikey Williams/Top Rank Inc via Getty Images Read more Superlek, Tonon Claim Big Wins At ONE Fight Night 12 WATCH: OnlyFans Model Flashes After Boxing Win Boxing'))